development:
  adapter: mysql
  database: raugstadinc_development
  username: root
  password: donkey
  host: localhost
  
test:
  adapter: mysql
  database: raugstadinc_test
  username: root
  password: donkey
  host: localhost